name: Build / Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup Node"
        uses: actions/setup-node@v3
      - name: "Install Node Packages"
        run: "npm install"
      - name: "Build Asar File"
        run: "npm run github-build"
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: "Create Release Draft"
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/castmate-deckboard.asar
          draft: true
          tag_name: v${{ steps.package-version.outputs.current-version}}
          
